// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbvUb1UC8ARavPyQMFLUA4HAbbqo_b7-A',
    appId: '1:412949760191:web:22b0bcdaf2da4a59c69e0a',
    messagingSenderId: '412949760191',
    projectId: 'chatapp-db494',
    authDomain: 'chatapp-db494.firebaseapp.com',
    storageBucket: 'chatapp-db494.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK51jLF9AgohnmKn5--KZrp_oHngqyUWY',
    appId: '1:412949760191:android:41a82edd28e99463c69e0a',
    messagingSenderId: '412949760191',
    projectId: 'chatapp-db494',
    storageBucket: 'chatapp-db494.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6AOgSMDegrfvE4wMvWOEArgh5UOU62YI',
    appId: '1:412949760191:ios:534d3da4419db7e1c69e0a',
    messagingSenderId: '412949760191',
    projectId: 'chatapp-db494',
    storageBucket: 'chatapp-db494.appspot.com',
    iosClientId: '412949760191-gbl7bi50htf4vcorcrvk212kg6g3gqj5.apps.googleusercontent.com',
    iosBundleId: 'com.example.messagemeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6AOgSMDegrfvE4wMvWOEArgh5UOU62YI',
    appId: '1:412949760191:ios:534d3da4419db7e1c69e0a',
    messagingSenderId: '412949760191',
    projectId: 'chatapp-db494',
    storageBucket: 'chatapp-db494.appspot.com',
    iosClientId: '412949760191-gbl7bi50htf4vcorcrvk212kg6g3gqj5.apps.googleusercontent.com',
    iosBundleId: 'com.example.messagemeApp',
  );
}
